#pragma config(Sensor, S1,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
#pragma config(Sensor, S4,     soundSensor,    sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int edge_check(int orientation,int x,int y,int XMAX,int YMAX,int XMIN,int YMIN);
int left(int orientation);
int right(int orientation);
void move();
void pickup();
void deliver(int orientation,int x,int y, int lightThreshold);

task main()
{
	nMotorPIDSpeedCtrl[motorC] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[motorB] = mtrSpeedReg;

	int lightThreshold=36;

	int orientation=0;
	//0 - East		[START]
	//1 - South
	//2 - West
	//3 - North
	//int grid[9][7];//grid[X][Y]
	int x=1,y=4;
	int XMAX=9,YMAX=7,XMIN=1,YMIN=1;
	int XSTART=1,YSTART=4;
	int edge_turn=0;
	int new_start=0;
	int skip=0;

	//Face North
	orientation=left(orientation);
	nxtDisplayTextLine(1,"%d: %d %d",orientation,x,y);
	wait1Msec(200);

	//While Clear
	while(SensorValue(sonarSensor)>10)
	{
		skip=0;

		//EDGE check
		edge_turn=edge_check(orientation,x,y,XMAX,YMAX,XMIN,YMIN);
		if(edge_turn==1)//manual orientation change
		{
			wait1Msec(200);
			orientation++;
			if(orientation==4)
			{
				orientation=0;
			}
			nxtDisplayTextLine(1,"%d: %d %d",orientation,x,y);
		}

		//IF NO Mine OR BLOCK - MOVE
		while(SensorValue(sonarSensor)>10 && SensorValue(lightSensor)>lightThreshold && skip==0)
		{
			//EDGE check
			edge_turn=edge_check(orientation,x,y,XMAX,YMAX,XMIN,YMIN);
			if(edge_turn==1)//manual orientation change
			{
				wait1Msec(200);
				orientation++;
				if(orientation==4)
				{
					orientation=0;
				}
				nxtDisplayTextLine(1,"%d: %d %d",orientation,x,y);
			}
			move();
			//CHANGE CO-ORDS [XY]
			if(orientation==0)
			{
				x++;
			}
			if(orientation==1)
			{
				y--;
			}
			if(orientation==2)
			{
				x--;
			}
			if(orientation==3)
			{
				y++;
			}
			nxtDisplayTextLine(1,"%d: %d %d",orientation,x,y);
			if(x==XSTART && y==YSTART)
			{
				skip=1;
			}
		}

		if(x==XSTART && y==YSTART)
		{
			skip=1;
		}
		//IF BACK AT START
		//IF Start[XSTART=XCUR && YSTART=YCUR]
		if(x==XSTART && y==YSTART)
		{
			nxtDisplayTextLine(3,"RESTARTING...");
			orientation=right(orientation);

			move();
			//CHANGE CO-ORDS [XY]
			if(orientation==0)
			{
				x++;
			}
			if(orientation==1)
			{
				y--;
			}
			if(orientation==2)
			{
				x--;
			}
			if(orientation==3)
			{
				y++;
			}
			nxtDisplayTextLine(1,"%d: %d %d",orientation,x,y);

			orientation=left(orientation);
			nxtDisplayTextLine(1,"%d: %d %d",orientation,x,y);

			XSTART++;

			XMAX--;
			YMAX--;
			XMIN++;
			YMIN++;
			//SKIP NEXT IF
			new_start=1;
		}

		//IF Mine
		if(SensorValue(lightSensor)<lightThreshold && new_start==0)
		{
			orientation=right(orientation);
			nxtDisplayTextLine(1,"%d: %d %d",orientation,x,y);

			//EDGE CHECK
			edge_turn=edge_check(orientation,x,y,XMAX,YMAX,XMIN,YMIN);
			if(edge_turn==1)
			{
				orientation++;
				if(orientation==4)
				{
					orientation=0;
				}
				nxtDisplayTextLine(1,"%d: %d %d",orientation,x,y);
					//EDGE CHECK
					edge_turn=edge_check(orientation,x,y,XMAX,YMAX,XMIN,YMIN);
					if(edge_turn==1)
					{
						orientation++;
						if(orientation==4)
						{
							orientation=0;
						}
						nxtDisplayTextLine(1,"%d: %d %d",orientation,x,y);
						skip=1;
					}
					wait1Msec(700);
				skip=1;
			}
			wait1Msec(700);


			/*
			//ANOTHER MINE
			if(SensorValue(lightSensor)<lightThreshold)
			{
				orientation=right(orientation);
				move();
				//CHANGE CO-ORDS [XY]
				if(orientation==0)
				{
					x++;
				}
				if(orientation==1)
				{
					y--;
				}
				if(orientation==2)
				{
					x--;
				}
				if(orientation==3)
				{
					y++;
				}
				orientation=left(orientation);
				/*
				//REFIND EDGE IF NEEDED
				while(SensorValue(lightSensor)>lightThreshold)
				{
					move();
                    if(SensorValue(lightSensor))
                    {
                        break;
                    }
					//CHANGE CO-ORDS [XY]
					if(orientation==0)
					{
						x++;
					}
					if(orientation==1)
					{
						y--;
					}
					if(orientation==2)
					{
						x--;
					}
					if(orientation==3)
					{
						y++;
					}
					orientation=left(orientation);
				}
				break;//BREAK OUT OF MINE IF STATEMENT COMPLETELY

			}
			*/

			//IF NO MINE / BLOCK - MOVE AROUND
			if(SensorValue(sonarSensor)>10 && SensorValue(lightSensor)>lightThreshold && skip==0)
			{
				move();
        if(SensorValue(sonarSensor)<10)
        {
            break;
        }
				//CHANGE CO-ORDS [XY]
				if(orientation==0)
				{
					x++;
				}
				if(orientation==1)
				{
					y--;
				}
				if(orientation==2)
				{
					x--;
				}
				if(orientation==3)
				{
					y++;
				}
				nxtDisplayTextLine(1,"%d: %d %d",orientation,x,y);
				orientation=left(orientation);
				nxtDisplayTextLine(1,"%d: %d %d",orientation,x,y);
			}

			if(SensorValue(sonarSensor)>10 && SensorValue(lightSensor)>lightThreshold && skip==0)
			{
				move();
	      if(SensorValue(sonarSensor)<10)
	      {
	          break;
	      }
				//CHANGE CO-ORDS [XY]
				if(orientation==0)
				{
					x++;
				}
				if(orientation==1)
				{
					y--;
				}
				if(orientation==2)
				{
					x--;
				}
				if(orientation==3)
				{
					y++;
				}
				nxtDisplayTextLine(1,"%d: %d %d",orientation,x,y);
				orientation=left(orientation);
				nxtDisplayTextLine(1,"%d: %d %d",orientation,x,y);
			}//END MOVE AROUND

		}//END IF MINE
	}//END WHILE CLEAR

	if(SensorValue(sonarSensor)<10)
	{
		pickup();
		//DELIVER
		deliver(orientation,x,y,lightThreshold);
	}//END WHILE BLOCK

}//END MAIN()

int edge_check(int orientation,int x,int y,int XMAX,int YMAX,int XMIN,int YMIN)
{
	//NW Corner
	if(orientation==3 && y==YMAX)
	{
		orientation=right(orientation);
		return(1);
	}

	//NE Corner
	if(orientation==0 && x==XMAX)
	{
		orientation=right(orientation);
		return(1);
	}

	//SE Corner
	if(orientation==1 && y==YMIN)
	{
		orientation=right(orientation);
		return(1);
	}

	//SW Corner
	if(orientation==2 && x==XMIN)
	{
		orientation=right(orientation);
		return(1);
	}

		return(0);
}

int left(int orientation)
{
	nMotorEncoder[motorB]=0;
	nMotorEncoder[motorC]=0;
	nMotorEncoderTarget[motorB]=170; //Rotations required for 90 degree turn
	nMotorEncoderTarget[motorC]=170; //Rotations required for 90 degree turn

	while(nMotorEncoder[motorB]<170 && nMotorEncoder[motorC]<170)
	{
		motor[motorB] = 30;
		motor[motorC] = -30;
	}
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(300);

	orientation--;
	if(orientation==-1)
	{
		orientation=3;
		return(orientation);
	}
	return(orientation);

}

int right(int orientation)
{
	nMotorEncoder[motorB]=0;
	nMotorEncoder[motorC]=0;
	nMotorEncoderTarget[motorB]=170; //Rotations required for 90 degree turn
	nMotorEncoderTarget[motorC]=170; //Rotations required for 90 degree turn

	while(nMotorEncoder[motorB]<170 && nMotorEncoder[motorC]<170)
	{
		motor[motorB] = -30;
		motor[motorC] = 30;
	}
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(300);

	orientation++;
	if(orientation==4)
	{
		orientation=0;
		return(orientation);
	}
	return(orientation);

}

void move()
{
	nMotorEncoder[motorB]=0;
	nMotorEncoder[motorC]=0;
	nMotorEncoderTarget[motorB]=280;
	nMotorEncoderTarget[motorC]=280;

	while(nMotorEncoder[motorB]<280 && nMotorEncoder[motorC]<280)
	{
		motor[motorB] = 30;
		motor[motorC] = 30;
	} // end while
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(500);
}

void pickup()
{
	nMotorEncoder[motorA]=0;
	nMotorEncoderTarget[motorA]=90; //Rotations required to pick up block

	motor[motorA] = -20;
	wait1Msec(1000);
}

void deliver(int orientation,int x,int y, int lightThreshold)
{
	int delivered=0;

	while(orientation!=0)
	{
		nMotorEncoder[motorB]=0;
		nMotorEncoder[motorC]=0;
		nMotorEncoderTarget[motorB]=170; //Rotations required for 90 degree turn
		nMotorEncoderTarget[motorC]=170; //Rotations required for 90 degree turn

		while(nMotorEncoder[motorB]<170 && nMotorEncoder[motorC]<170)
		{
			motor[motorB] = -30;
			motor[motorC] = 30;
		}
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(300);

		orientation++;
		if(orientation==4)
		{
			orientation=0;
		}
	}//END WHILE

	while(delivered==0)
	{
		while(SensorValue(lightSensor)>lightThreshold && delivered==0)
		{
			move();
			//CHANGE CO-ORDS [XY]
				if(orientation==0)
				{
					x++;
				}
				if(orientation==1)
				{
					y--;
				}
				if(orientation==2)
				{
					x--;
				}
				if(orientation==3)
				{
					y++;
				}
				nxtDisplayTextLine(1,"%d: %d %d",orientation,x,y);
				if(x==10)
				{
					delivered=1;
				}
		}
		while(SensorValue(lightSensor)<lightThreshold && delivered==0)
		{
			orientation=right(orientation);
			move();
			//CHANGE CO-ORDS [XY]
				if(orientation==0)
				{
					x++;
				}
				if(orientation==1)
				{
					y--;
				}
				if(orientation==2)
				{
					x--;
				}
				if(orientation==3)
				{
					y++;
				}
				nxtDisplayTextLine(1,"%d: %d %d",orientation,x,y);
				orientation=left(orientation);
				if(x==10)
				{
					delivered=1;
				}
		}
	}
}
